services:
  api_app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - network

  api:
    image: nginx:alpine
    depends_on:
      - api_app
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
    volumes:
      - volume:/var/lib/mysql
    networks:
      - network

volumes:
  volume:

networks:
  network:
    driver: bridge
